### ISSUE TITLE
Versión 3.13.1 incompatible con plugin YITH WooCommerce Checkout Manager

### ISSUE THREAD

**Issue by Rewebs** [mobbexco/woocommerce#197]
Esta ultima version provoca error fatal al generarse las ordenes.
Tambien se puede ver este tipo de error al ingresar a la seccion Pedidos:

```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/sitio/public_html/wp-content/plugins/woocommerce-mobbex/Observer/Checkout.php:72
Stack trace:
#0 /home/sitio/public_html/wp-includes/class-wp-hook.php(310): Mobbex\WP\Checkout\Observer\Checkout->add_checkout_fields(Array)
#1 /home/sitio/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /home/sitio/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(1648): apply_filters('woocommerce_bil...', Array, 'XX')
#3 /home/sitio/public_html/wp-content/plugins/yith-woocommerce-checkout-manager/includes/functions.ywccp.php(377): WC_Countries->get_address_fields('XX', 'billing_')
#4 /home/sitio/public_html/wp-content/plugins/yith-woocommerce-checkout-manager/includes/functions.ywccp.php(350): ywccp_get_default_fields('billing')
#5 /home/sitio/public_html/wp-content/plugins/yith-woocommerce-checkout-manager/includes/functions.ywccp.php(96): ywccp_get_default_fields_key('billing')
#6 /ho in /home/sitio/public_html/wp-content/plugins/woocommerce-mobbex/Observer/Checkout.php on line 72
```

Por ahora lo he solucionado volviendo a la version anterior 3.12.0

**Comment by jlmobbex** [comment]
Hola @Rewebs! Gracias por tu comentario, estamos revisando el inconveniente.

**Comment by jlmobbex** [comment]
Buenas @Rewebs ! Este problema quedó resuelto el año pasado (en #213), pero no actualizamos la issue debido a que durante el año pasado no utilizamos este canal. Si aún continúa el problema te pido que pruebes utilizando la versión más reciente del plugin y sino se resuelve que abras una nueva issue con los detalles actualizados
